version: 2

# Each job represents a phase in the Build-Test-Deploy process
jobs:

  build:
    # This is the directory into which our code will be checked out, and this path will be used as the default working directory for the rest of the job
    working_directory: ~/code

    # Container images
    docker:
      - image: circleci/android:api-27-alpha

    environment:
      JVM_OPTS: -Xmx3200m

    branches:
      only:
        - master
        - testbranch

    steps:

      # We start with checkout so we can operate on the codebase.
      - checkout

      # Pull down the cache, if present
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      #- run:
      #   name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
      #   command: sudo chmod +x ./gradlew

      # Pull down the project’s dependencies
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      # Store the dependencies in order to speed things up for next time
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      # Run the unit tests, and run the built in linting tools to check your code for style issues
      - run:
          name: Run Tests
          command: ./gradlew lint test

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_test_results:
          path: app/build/test-results

      - store_artifacts:
          path: app/build/outputs/apk/
          destination: /apk/
